<%@ Page Language="C#" AutoEventWireup="true"  MasterPageFile="/_masterpages/Site.master" Inherits="System.Web.UI.Page" %>
<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>        
        <div>            
            <h2>
                Contry code
            </h2>
            <p>
                you can choose what countries do you wish to show. Multiple selection (comma separated).<br />                               
            </p>
            <h2>Useage</h2>
            <p>
                countrycode=UK,EMU,US
            </p>              
            <ul><li>
                AR</li><li>
AU</li><li>
AT</li><li>
BE</li><li>
BR</li><li>
CA</li><li>
CL</li><li>
CN</li><li>
CO</li><li>
CZ</li><li>
DK</li><li>
EMU</li><li>
FI</li><li>
FR</li><li>
DE</li><li>
GR</li><li>
HK</li><li>
HU</li><li>
IS</li><li>
IN</li><li>
ID</li><li>
IE</li><li>
IT</li><li>
JP</li><li>
MX</li><li>
NL</li><li>
NZ</li><li>
NO</li><li>
PL</li><li>
PT</li><li>
RO</li><li>
RU</li><li>
SG</li><li>
SK</li><li>
ZA</li><li>
ES</li><li>
SE</li><li>
CH</li><li>
TR</li><li>
UK</li><li>
US</li>
            </ul>
            <h2>Sample</h2>
            <p>
                http://calendar.fxstreet.com/eventdate/?countrycode=UK,EMU,US&k={YOUR_CLIENT_KEY}&s={HASH}&t={TIMESTAMP}
            </p>                          
        </div>        
    </div>
</asp:Content>